spring:
  # h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2.console.enabled: true

  # console color
  output:
    ansi:
      enabled: always

  # osiv
  jpa:
    open-in-view: false
